### ISSUE TITLE
revChatGPT  config.json  错误  mac

### ISSUE THREAD

**Issue by zlc000190** [yihong0618/xiaogpt#107]
python3 -m revChatGPT.V1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 157, in _get_module_details
    code = loader.get_code(mod_name)
  File "", line 1017, in get_code
  File "", line 947, in source_to_code
  File "", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/revChatGPT/V1.py", line 360
    "access_tokens":{"[someone@example.com](mailto:someone@example.com)": 'this account's access token', }

**Comment by yihong0618** [comment]
@zlc000190 最好用 openai api 现在
你这个属于上游的错误，可以到上游提 issue~~

**Comment by pjq** [comment]
revChatGPT 已删除 默认可以使用chat API
