### ISSUE TITLE
按照YouTube影片进行设置，一切正常，运行时每当小爱回答问题时就会报错退出，以下是报错信息

### ISSUE THREAD

**Issue by jtxql** [yihong0618/xiaogpt#114]
Running xiaogpt now, 用`帮我`开头来提问
Traceback (most recent call last):
  File "xiaogpt.py", line 523, in <module>
    asyncio.run(miboy.run_forever())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "xiaogpt.py", line 365, in run_forever
    if query.startswith(KEY_WORD):
TypeError: startswith first arg must be str or a tuple of str, not list

**Comment by yihong0618** [comment]
我们修复下

**Comment by yihong0618** [comment]
拉下代码再试一下？

**Comment by jtxql** [comment]
谢谢，这个问题确实解决了。但是还有一个小问题，每次问问题，小爱总是先抢先回答半句，然后开始询问chatgpT。

**Comment by yihong0618** [comment]
这个是已经问题，有完整 mute 小爱的办法，但是需要频繁请求，我们采用的这种办法

**Comment by jtxql** [comment]
明白了，谢谢。对了，我还有个建议，最好能做成一个程序可以控制家里多台小爱音箱。
