### ISSUE TITLE
Windows运行micli.py list登录失败，SSLcontext的错误，大家遇到过吗？

### ISSUE THREAD

**Issue by Cosamli** [yihong0618/xiaogpt#119]
Exception on login None: ssl should be SSLContext, bool, Fingerprint or None, got False instead.
Traceback (most recent call last):
  File "C:\Users\cosam\AppData\Roaming\Python\Python39\site-packages\miservice\miaccount.py", line 56, in login
    resp = await self._serviceLogin(f"serviceLogin?sid={sid}&_json=true")
  File "C:\Users\cosam\AppData\Roaming\Python\Python39\site-packages\miservice\miaccount.py", line 98, in _serviceLogin
    async with self.session.request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\client.py", line 402, in _request
    ssl = _merge_ssl_params(ssl, verify_ssl, ssl_context, fingerprint)
  File "C:\ProgramData\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 192, in _merge_ssl_params
    raise TypeError(
TypeError: ssl should be SSLContext, bool, Fingerprint or None, got False instead.
Error https://api.io.mi.com/app/home/device_list: Login failed

**Comment by yihong0618** [comment]
参考 #41
