### ISSUE TITLE
前面几步都做了，为啥跑不起来？

### ISSUE THREAD

**Issue by lichengda** [yihong0618/xiaogpt#13]
ython3 xiaogpt.py --hardware LX06
Traceback (most recent call last):
  File "/root/xiaomivoice/xiaogpt/xiaogpt.py", line 238, in <module>
    asyncio.run(miboy.run_forever())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/xiaomivoice/xiaogpt/xiaogpt.py", line 163, in run_forever
    await self.init_all_data(session)
  File "/root/xiaomivoice/xiaogpt/xiaogpt.py", line 65, in init_all_data
    self.service_token = user_data.get("micoapi")[1]
TypeError: 'NoneType' object is not subscriptable

**Comment by yihong0618** [comment]
@lichengda 修复了，拉一下最新代码再跑一遍试试？

**Comment by lichengda** [comment]
@yihong0618 大佬，可以跑起来了。但是怎么提问启动呢。

**Comment by yihong0618** [comment]
帮我回答作为开头，“帮我回答王小波怎么样”

**Comment by lichengda** [comment]
@yihong0618 大佬，让我跪舔你，哈哈

**Comment by yihong0618** [comment]
@lichengda 先关了哈，你可以根据源码改自己的提示词。

**Comment by lichengda** [comment]
大佬请收下我的膝盖

**Comment by yihong0618** [comment]
> 大佬请收下我的膝盖

哈哈哈哈哈
