### ISSUE TITLE
只使用cookie时，回答完毕后会提示报错「illegal argument exception」

### ISSUE THREAD

**Issue by yuyongID** [yihong0618/xiaogpt#134]
运行：`python3 xiaogpt.py --use_command --hardware S12 --cookie 'xxxxxx' --use_chatgpt_api`
结果：
```bash
Running xiaogpt now, 用`帮我/请回答`开头来提问
或用`开始持续对话`开始持续对话
--------------------
问题：法国总统是谁？
以下是小爱的回答:  法国的总统是埃马纽埃尔·马克龙
以下是GPT的回答: 法国总统是马克龙（Emmanuel--Macron）。
Traceback (most recent call last):
  File "/Users/dengyu/ScriptWork/python/xiaogpt/xiaogpt.py", line 5, in <module>
    main()
  File "/Users/dengyu/ScriptWork/python/xiaogpt/xiaogpt/cli.py", line 87, in main
    asyncio.run(miboy.run_forever())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/dengyu/ScriptWork/python/xiaogpt/xiaogpt/xiaogpt.py", line 282, in run_forever
    await self.do_tts(message, wait_for_finish=True)
  File "/Users/dengyu/ScriptWork/python/xiaogpt/xiaogpt/xiaogpt.py", line 178, in do_tts
    if not await self.get_if_xiaoai_is_playing():
  File "/Users/dengyu/ScriptWork/python/xiaogpt/xiaogpt/xiaogpt.py", line 195, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
  File "/Users/dengyu/.local/share/virtualenvs/xiaogpt-MqYRciPz/lib/python3.10/site-packages/miservice/minaservice.py", line 68, in player_get_status
    return await self.ubus_request(
  File "/Users/dengyu/.local/share/virtualenvs/xiaogpt-MqYRciPz/lib/python3.10/site-packages/miservice/minaservice.py", line 32, in ubus_request
    result = await self.mina_request(
  File "/Users/dengyu/.local/share/virtualenvs/xiaogpt-MqYRciPz/lib/python3.10/site-packages/miservice/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
  File "/Users/dengyu/.local/share/virtualenvs/xiaogpt-MqYRciPz/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {"code":601,"message":"illegal argument exception","data":"IllegalArgumentException: ubus call format illegal!"}
```
排查：当我把`self.device_id = "xxxx"`默认不止之后，就不会产生这个错误。
盲猜：`get_if_xiaoai_is_playing`函数为考虑单独使用`cookeis`情况，无`device_id`

**Comment by yihong0618** [comment]
把 —account —password 加上

**Comment by yuyongID** [comment]
> 把 —account —password 加上

我的账号下的设备列表没有这个音箱，加账号也不管用。但是登录小爱的APP却可以正常使用。我觉得可以从输入的`cookies`里面抽取出`device_id`。字符串里是有这个参数的。

**Comment by yihong0618** [comment]
可以，来个 PR 试试？

**Comment by yihong0618** [comment]
@yuyongID 我来 fix 看看。

**Comment by yihong0618** [comment]
@yuyongID 修复了
