### ISSUE TITLE
ModuleNotFoundError: No module named 'edge_tts'

### ISSUE THREAD

**Issue by huanjie** [yihong0618/xiaogpt#149]
MiService 和　revChatGPT.V3　都装了，为什么还缺edge_tts呢
[centos@centos8 xiaogpt]$ xiaogpt --hardware LX01  --mute_xiaoai --use_chatgpt_api
Traceback (most recent call last):
  File "/home/centos/.local/bin/xiaogpt", line 5, in <module>
    from xiaogpt.cli import main
  File "/home/centos/.local/lib/python3.9/site-packages/xiaogpt/cli.py", line 5, in <module>
    from xiaogpt.xiaogpt import MiGPT
  File "/home/centos/.local/lib/python3.9/site-packages/xiaogpt/xiaogpt.py", line 17, in <module>
    import edge_tts
ModuleNotFoundError: No module named 'edge_tts'

**Comment by huanjie** [comment]
pip3.9  install edge-tts
