### ISSUE TITLE
在windows下执行 micli.py list 会弹出窗口闪退

### ISSUE THREAD

**Issue by nijunhui** [yihong0618/xiaogpt#15]
也不知道有没有正确登录账号和读取设备列表

**Comment by yihong0618** [comment]
python3 xiaogpt.py --hardware LX06 --account ${your_xiaomi_account} --password ${your_password};

试试这个命令，LX06 改成你的硬件

**Comment by nijunhui** [comment]
> python3 xiaogpt.py --hardware LX06 --account yourxiaomiaccount−−password{your_password};
> 
> 试试这个命令，LX06 改成你的硬件

可以执行了。不过小爱音箱不在身边，会报以下错误，晚上回家再试试

Traceback (most recent call last):
  File "C:\Users\username\Documents\xiaogpt\xiaogpt.py", line 303, in <module>
    asyncio.run(miboy.run_forever())
  File "C:\Users\username\.conda\envs\migpt\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\username\.conda\envs\migpt\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\username\Documents\xiaogpt\xiaogpt.py", line 187, in run_forever
    await self.init_all_data(session)
  File "C:\Users\username\Documents\xiaogpt\xiaogpt.py", line 80, in init_all_data
    await self._init_first_data_and_chatbot()
  File "C:\Users\username\Documents\xiaogpt\xiaogpt.py", line 118, in _init_first_data_and_chatbot
    self.last_timestamp, self.last_record = self.get_last_timestamp_and_record(data)
  File "C:\Users\username\Documents\xiaogpt\xiaogpt.py", line 133, in get_last_timestamp_and_record
    last_record = records[0]
IndexError: list index out of range
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F7B69B8820>
Traceback (most recent call last):
  File "C:\Users\username\.conda\envs\migpt\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\username\.conda\envs\migpt\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\username\.conda\envs\migpt\lib\asyncio\base_events.py", line 751, in call_soon
    self._check_closed()
  File "C:\Users\username\.conda\envs\migpt\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by yihong0618** [comment]
我晚上也看看

**Comment by yihong0618** [comment]
@nijunhui 我这边测试没问题，手头没 windows 没法测试，如果再有问题 @ 我一下。

**Comment by nijunhui** [comment]
> @nijunhui 我这边测试没问题，手头没 windows 没法测试，如果再有问题 @ 我一下。

测试了一下，还是报一样的错误。可能是调用aiohttp里的ClientSession方法没有得到session值，导致下面get_last_timestamp_and_record失败

**Comment by yihong0618** [comment]
可能是 chatgpt 报的错，先确保 revchatgpt 能跑

**Comment by nijunhui** [comment]
> 

能跑的，可以直接用

**Comment by yihong0618** [comment]
@nijunhui 
self.last_timestamp, self.last_record = self.get_last_timestamp_and_record(data)
File "C:\Users\username\Documents\xiaogpt\xiaogpt.py", line 133, in get_last_timestamp_and_record
last_record = records[0]
IndexError: list index out of range

这块的问题，你先跟小爱随便聊聊。再跑这个

**Comment by nijunhui** [comment]
> 
测了好久，还是不行

**Comment by yihong0618** [comment]
尝试下抓包的方式。

**Comment by nijunhui** [comment]
> 尝试下抓包的方式。
是在局域网里抓访问这个链接的cookie吗？
https://userprofile.mina.mi.com/device_profile/v2/conversation

**Comment by yihong0618** [comment]
可以用手机抓包。

**Comment by nijunhui** [comment]
Exception on login 4******2: {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
这个登录失败是什么原因？账号密码都对的

**Comment by yihong0618** [comment]
看起来小米封了这个我明天再看一下

**Comment by yihong0618** [comment]
我这里测试了没问题。
可以试试用 `--account {account} --password {password}` 启动
