### ISSUE TITLE
程序运行但是无法监听到音箱的语音输入

### ISSUE THREAD

**Issue by yhwymy** [yihong0618/xiaogpt#173]
调试了一下，task变量可以有值，但是poll_latest_ask()方法并没有执行，然后程序就一直在await self.new_record_event.wait()，这里阻塞了，请大神帮忙给看看咋回事儿。
```
    async def run_forever(self):
        async with ClientSession() as session:
            print(session)
            await self.init_all_data(session)
            task = asyncio.create_task(self.poll_latest_ask())
            print(task)
            assert task is not None  # to keep the reference to task, do not remove this
            print(f"Running xiaogpt now, 用`{'/'.join(self.config.keyword)}`开头来提问")
            print(f"或用`{self.config.start_conversation}`开始持续对话")
            while True:
                print("1")
                self.polling_event.set()
                print('2')
                await self.new_record_event.wait()
```

**Comment by yihong0618** [comment]
@frostming 
请确认 micli list 和 micli mina 能执行

**Comment by yhwymy** [comment]
使用docker 部署的时候又报这个错。实在是困惑啊。
root@hecs-156294:~# docker run -v /root/xiaogpt:/config yihong0618/xiaogpt --config=/config/config.json
Exception on login {userid}: 'userId'
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 71, in login
    self.token["userId"] = resp["userId"]
KeyError: 'userId'
Exception on login {userid}: 'userId'
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 71, in login
    self.token["userId"] = resp["userId"]
KeyError: 'userId'
Traceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 105, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/xiaogpt/xiaogpt.py", line 380, in run_forever
    await self.init_all_data(session)
  File "/app/xiaogpt/xiaogpt.py", line 104, in init_all_data
    await self._init_data_hardware()
  File "/app/xiaogpt/xiaogpt.py", line 126, in _init_data_hardware
    hardware_data = await self.mina_service.device_list()
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 27, in device_list
    result = await self.mina_request("/admin/v2/device_list?master=" + str(master))
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_Bz5mvj8rDcLeHIA1KtVu4Y62fE7Piw: Login failed

**Comment by TyTheLoser** [comment]
> @frostming 请确认 micli list 和 micli mina 能执行

能执行

**Comment by ggwgit** [comment]
poll_latest_ask  一直监听不到小爱的语音输入，我也有同样的问题，是否需要小米IoT开放平台上面配置些什么吗？

**Comment by yihong0618** [comment]
先关了，有更多信息欢迎随时打开

**Comment by 6vision** [comment]
问题+1 ，国内阿里云服务器，怎么解决？
