### ISSUE TITLE
AttributeError: 'MiNAService' object has no attribute 'player_get_status'

### ISSUE THREAD

**Issue by cathyliuchen** [yihong0618/xiaogpt#178]
Running xiaogpt now, 用`帮我/请回答`开头来提问
或用`开始持续对话`开始持续对话
开始对话
Traceback (most recent call last):
  File "xiaogpt.py", line 5, in <module>
    main()
  File "/Users/cathy/PROJECT/xiaoGPT/xiaogpt/xiaogpt/cli.py", line 105, in main
    loop.run_until_complete(miboy.run_forever())
  File "/Users/cathy/PROJECT/xiaoGPT/xiaoGPTenv/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/cathy/PROJECT/xiaoGPT/xiaogpt/xiaogpt/xiaogpt.py", line 400, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/Users/cathy/PROJECT/xiaoGPT/xiaogpt/xiaogpt/xiaogpt.py", line 368, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "/Users/cathy/PROJECT/xiaoGPT/xiaogpt/xiaogpt/xiaogpt.py", line 359, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
AttributeError: 'MiNAService' object has no attribute 'player_get_status'

ps: 在xiaoGPT总目录（包括xiaogpt和MiService）下创建了虚拟环境xiaoGPTenv  （python3.8），所有的安装命令都在该虚拟环境中，miservice和xiaogpt相关包都安装于此。

**Comment by yihong0618** [comment]
pip uninstall miservice

pip install -U miservice_fork

**Comment by Wanghongchao91** [comment]
我也是这样

Running xiaogpt now, 用`帮我`开头来提问
{'account': <miservice.miaccount.MiAccount object at 0x7f1410dcef10>}
Traceback (most recent call last):
  File "xiaogpt.py", line 493, in <module>
    asyncio.run(miboy.run_forever())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "xiaogpt.py", line 349, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "xiaogpt.py", line 316, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "xiaogpt.py", line 307, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
AttributeError: 'MiNAService' object has no attribute 'player_get_status'

**Comment by yihong0618** [comment]
我上面写着解决方法啊

**Comment by easin** [comment]
> 我上面写着解决方法啊


继续报错：
  ~/Downloads/xatx/xiaogpt-main  python3.9 xiaogpt.py --hardware LX06  --mute_xiaoai --use_chatgpt_api                                        Traceback (most recent call last):
  File "/Users/easin/Downloads/xatx/xiaogpt-main/xiaogpt.py", line 2, in <module>
    from xiaogpt.cli import main
  File "/Users/easin/Downloads/xatx/xiaogpt-main/xiaogpt/cli.py", line 5, in <module>
    from xiaogpt.xiaogpt import MiGPT
  File "/Users/easin/Downloads/xatx/xiaogpt-main/xiaogpt/xiaogpt.py", line 22, in <module>
    from miservice import MiAccount, MiIOService, MiNAService, miio_command
ImportError: cannot import name 'MiAccount' from 'miservice' (unknown location)

**Comment by mutefrank** [comment]
> > 我上面写着解决方法啊
> 
> 继续报错：  ~/Downloads/xatx/xiaogpt-main  python3.9 xiaogpt.py --hardware LX06 --mute_xiaoai --use_chatgpt_api Traceback (most recent call last): File "/Users/easin/Downloads/xatx/xiaogpt-main/xiaogpt.py", line 2, in from xiaogpt.cli import main File "/Users/easin/Downloads/xatx/xiaogpt-main/xiaogpt/cli.py", line 5, in from xiaogpt.xiaogpt import MiGPT File "/Users/easin/Downloads/xatx/xiaogpt-main/xiaogpt/xiaogpt.py", line 22, in from miservice import MiAccount, MiIOService, MiNAService, miio_command ImportError: cannot import name 'MiAccount' from 'miservice' (unknown location)

报同样的错误，请问有无解决方案？
