### ISSUE TITLE
ubuntu环境下使用命令是正常的，但是使用脚本就报错了

### ISSUE THREAD

**Issue by Kill4peacE** [yihong0618/xiaogpt#189]
脚本如下：
{
    "hardware": "LX06",
    "account": "XXX",
    "password": "XXX",
    "openai_key": "XXX",
    "cookie": "",
    "mi_did": "XXX",
    "use_command": false,
    "mute_xiaoai": true,
    "verbose": false,
    "bot": "chatgptapi",
    "enable_edge_tts": false,
    "edge_tts_voice": "zh-CN-XiaoxiaoNeural",
    "keyword": ["帮我", "请回答"],
    "start_conversation": "开始持续对话",
    "end_conversation": "结束持续对话",
    "stream": true,
    "proxy": "",
    "gpt_options": {}
}
报错如下，我路由器带FQ，所以我不需要部署代理：
root@k4p-virtual-machine:/home/k4p/xiaogpt# python3 xiaogpt.py --config xiao_config.json
Traceback (most recent call last):
  File "/home/k4p/xiaogpt/xiaogpt.py", line 5, in <module>
    main()
  File "/home/k4p/xiaogpt/xiaogpt/cli.py", line 106, in main
    config = Config.from_options(options)
  File "/home/k4p/xiaogpt/xiaogpt/config.py", line 90, in from_options
    config.read_from_config(options.config)
  File "/home/k4p/xiaogpt/xiaogpt/config.py", line 112, in read_from_config
    validate_proxy(value)
  File "/home/k4p/xiaogpt/xiaogpt/utils.py", line 59, in validate_proxy
    raise ValueError("Proxy scheme must be http or https")
ValueError: Proxy scheme must be http or https
注释掉proxy一行，报错如下：
Traceback (most recent call last):
  File "/home/k4p/xiaogpt/xiaogpt.py", line 5, in <module>
    main()
  File "/home/k4p/xiaogpt/xiaogpt/cli.py", line 106, in main
    config = Config.from_options(options)
  File "/home/k4p/xiaogpt/xiaogpt/config.py", line 90, in from_options
    config.read_from_config(options.config)
  File "/home/k4p/xiaogpt/xiaogpt/config.py", line 100, in read_from_config
    config = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 18 column 5 (char 502)

**Comment by frostming** [comment]
别注释(json里面不允许注释）直接删掉就好了
