### ISSUE TITLE
大佬，昨晚可以正常运行，今天运行提示“未授权的服务id”

### ISSUE THREAD

**Issue by Flavored4179** [yihong0618/xiaogpt#26]
小爱音箱是`L05C`，昨晚可以正常运行，终端有ChatGTP的回答，但小爱没有说出来。
今天运行提示以下错误：
```bash
{'code': 21315, 'result': 'error', 'desc': '未授权的服务id', 'description': '未授权的服务id'}
2023-02-26 20:42:03,175 - miservice - ERROR - login - Exception on login : 'qs'
Traceback (most recent call last):
  File "/Users/xxx/gitlab/xiaogpt/venv/lib/python3.10/site-packages/miservice/miaccount.py", line 63, in login
    'qs': resp['qs'],
KeyError: 'qs'
Traceback (most recent call last):
  File "/Users/xxx/gitlab/xiaogpt/xiaogpt.py", line 300, in <module>
    asyncio.run(miboy.run_forever())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/xxx/gitlab/xiaogpt/xiaogpt.py", line 186, in run_forever
    await self.init_all_data(session)
  File "/Users/xxx/gitlab/xiaogpt/xiaogpt.py", line 73, in init_all_data
    await self._init_data_hardware()
  File "/Users/xxx/gitlab/xiaogpt/xiaogpt.py", line 96, in _init_data_hardware
    hardware_data = await self.mina_service.device_list()
  File "/Users/xxx/gitlab/xiaogpt/venv/lib/python3.10/site-packages/miservice/minaservice.py", line 23, in device_list
    result = await self.mina_request('/admin/v2/device_list?master=' + str(master))
  File "/Users/xxx/gitlab/xiaogpt/venv/lib/python3.10/site-packages/miservice/minaservice.py", line 20, in mina_request
    return await self.account.mi_request('/usr/local/bin/micli.py', 'https://api2.mina.mi.com' + uri, data, headers)
  File "/Users/xxx/gitlab/xiaogpt/venv/lib/python3.10/site-packages/miservice/miaccount.py", line 135, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_SQIFrmafJepRGlDL3: Login failed
```
`micli list`和`micli mina`都能正常输出，通过`--account`和`--password`参数传入账号密码也是一样的错误。

**Comment by yihong0618** [comment]
用 micli 看看可以 tts 不

**Comment by Flavored4179** [comment]
可以正常播报文本。
`/usr/local/bin/micli.py 5-3 明天天气怎么样`

**Comment by yihong0618** [comment]
rm ~/.mi.token
再执行带 `--account` `--password`的

**Comment by yihong0618** [comment]
@Flavored4179 可以了么

**Comment by Flavored4179** [comment]
大佬不行，没有这个文件，重新执行还是一样的错误。
```
rm ~/.mi.token
rm: /Users/xxx/.mi.token: No such file or directory
```
> rm ~/.mi.token 再执行带 `--account` `--password`的

**Comment by yihong0618** [comment]
@Flavored4179 拉一下最新代码，再试验一下

**Comment by Flavored4179** [comment]
谢谢大佬，最新代码可以正常运行了。但音箱只播报小爱的回答，`GTP`回答无法播报。
```
以下是小爱的回答:
中国四大发明有造纸术、指南针、火药和印刷术，这四种凝结着古代人民智慧的发明对整个世界都有着巨大的影响，关于四大发明的说法最早是由英国汉学家艾约瑟提出来的，而且
也得到了其他历史学家的认可。
以下是GPT的回答:中国的四大发明是指造纸术、指南针、火药和印刷术。这些发明在中国历史上具有重要的地位，不仅对中国自身的文化和科技进步做出了巨大贡献，也对世界
文明进程产生了深远影响。造纸术改变了信息传播的方式，指南针促进了世界贸易的发展，火药革新了战争方式，印刷术则大大促进了知识的传播和普及化。
```

**Comment by yihong0618** [comment]
@Flavored4179 
找到 tts 命令，然后加上 `--use_command` 试试

**Comment by yihong0618** [comment]
@Flavored4179 有可能是蓝牙出现问题了，重启小爱 -> 用 app 确定蓝牙打开了 -> 再试试

**Comment by Flavored4179** [comment]
将`micli`改成`subprocess.check_output(["/usr/local/bin/micli.py", self.tts_command, value])`我自己本机的路径，使用`--use_command`可以正常使用了。感觉大佬的耐心解答，祝你好梦。

**Comment by yihong0618** [comment]
客气了

**Comment by Fason110** [comment]
s505@debian:~/xiaogpt-main$ python3 xiaogpt.py --hardware MDZ-25-DA
Traceback (most recent call last):
  File "/home/s505/xiaogpt-main/xiaogpt.py", line 305, in <module>
    asyncio.run(miboy.run_forever())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/s505/xiaogpt-main/xiaogpt.py", line 190, in run_forever
    await self.init_all_data(session)
  File "/home/s505/xiaogpt-main/xiaogpt.py", line 75, in init_all_data
    await self._init_data_hardware()
  File "/home/s505/xiaogpt-main/xiaogpt.py", line 106, in _init_data_hardware
    raise Exception(f"we have no hardware: {self.hardware} please check")
Exception: we have no hardware: MDZ-25-DA please check
s505@debian:~/xiaogpt-main$
请问大佬，这个小爱型号是否能帮忙适配？一直初始化不成功

**Comment by yihong0618** [comment]
@Fason110 这个好像不支持

**Comment by Fason110** [comment]
搞定了，支持的，硬件型号是S12。谢谢大师。另外，GPT反应好像很慢，我调你的代码都无法加快，不知道有没办法加快回答速度发自我的手机-------- 原始邮件 --------发件人： yihong ***@***.***>日期： 2023年2月27日周一 晚上10:14收件人： yihong0618/xiaogpt ***@***.***>抄送： Fason110 ***@***.***>, Mention ***@***.***>主    题： Re: [yihong0618/xiaogpt] 大佬，昨晚可以正常运行，今天运行提示“未授权的服务id” (Issue #26)

@Fason110 这个好像不支持

**Comment by yihong0618** [comment]
@Fason110 
- 买 plus
- 用英语问（改 prompt)

**Comment by Fason110** [comment]
是plus。我明天试试换英语。另外，现在V2可用吗？效果会否好些？V2使用指南？

yihong ***@***.***> 于2023年2月28日周二 19:06写道：

**Comment by yihong0618** [comment]
V2 被封了。
