### ISSUE TITLE
还是有问题

### ISSUE THREAD

**Issue by kindom2008** [yihong0618/xiaogpt#266]
(base) kindom2008@kindomAi:~/THUDM/xiaogpt$ python3 xiaogpt.py --hardware S12A --use_chatgpt_api   --stream  --enable_edge_tts
[05/20/23 15:23:27] INFO     Serving on 172.30.215.132:8083                                                                                                                          xiaogpt.py:294
Running xiaogpt now, 用`帮我/请回答`开头来提问
或用`开始持续对话`开始持续对话
--------------------
问题：在五二零这一天对我老婆说几句话？
以下是小爱的回答:  看见你们幸福的样子，我也好开心
以下是GPT的回答: [05/20/23 15:23:49] ERROR    <empty message>                                                                                                                                         xiaogpt.py:375
回答完毕
开始对话
Traceback (most recent call last):
  File "/home/kindom2008/THUDM/xiaogpt/xiaogpt.py", line 5, in <module>
    main()
  File "/home/kindom2008/THUDM/xiaogpt/xiaogpt/cli.py", line 136, in main
    loop.run_until_complete(miboy.run_forever())
  File "/home/kindom2008/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/kindom2008/THUDM/xiaogpt/xiaogpt/xiaogpt.py", line 440, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/home/kindom2008/THUDM/xiaogpt/xiaogpt/xiaogpt.py", line 408, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "/home/kindom2008/THUDM/xiaogpt/xiaogpt/xiaogpt.py", line 399, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
AttributeError: 'MiNAService' object has no attribute 'player_get_status'
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<MiGPT.poll_latest_ask() running at /home/kindom2008/THUDM/xiaogpt/xiaogpt/xiaogpt.py:102> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object MiGPT.poll_latest_ask at 0x7f53d4fde340>
RuntimeError: coroutine ignored GeneratorExit

**Comment by yihong0618** [comment]
pip uninstall miservice
pip install miservice_fork

**Comment by yihong0618** [comment]
我把你上一个相同的关了。
