### ISSUE TITLE
在接收到小爱的文字之后进行报错

### ISSUE THREAD

**Issue by miuziyu** [yihong0618/xiaogpt#269]
![image](https://github.com/yihong0618/xiaogpt/assets/75081425/ff8330ed-dd87-4c4f-bfd4-f623f16dd5b1)
问题：写诗？
Traceback (most recent call last):
  File "E:\xiaogpt-main\xiaogpt.py", line 5, in <module>
    main()
  File "E:\xiaogpt-main\xiaogpt\cli.py", line 110, in main
    loop.run_until_complete(miboy.run_forever())
  File "C:\Users\47049\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\xiaogpt-main\xiaogpt\xiaogpt.py", line 449, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "E:\xiaogpt-main\xiaogpt\xiaogpt.py", line 392, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "E:\xiaogpt-main\xiaogpt\xiaogpt.py", line 383, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
AttributeError: 'MiNAService' object has no attribute 'player_get_status'

**Comment by yihong0618** [comment]
pip uninstall miservice
pip install miservice_fork
