### ISSUE TITLE
小爱回答时报错

### ISSUE THREAD

**Issue by woiweb** [yihong0618/xiaogpt#277]
`python3 xiaogpt.py --hardware LX04  --mute_xiaoai --use_gpt3

Running xiaogpt now, 用`帮我/请回答`开头来提问
或用`开始持续对话`开始持续对话
--------------------
问题：一加一等于几？
Traceback (most recent call last):
  File "/Users/xxx/dev/gpt/xiaogpt/xiaogpt.py", line 5, in <module>
    main()
  File "/Users/xxxx/dev/gpt/xiaogpt/xiaogpt/cli.py", line 136, in main
    loop.run_until_complete(miboy.run_forever())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/xxx/dev/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 466, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/Users/xxxx/dev/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 408, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaoqiang/xxxx/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 399, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MiNAService' object has no attribute 'player_get_status'`

每次问一下，帮我xxx，然后就挂了。

**Comment by yihong0618** [comment]
pip uninstall miservice
pip install -U miservice_fork
