### ISSUE TITLE
运行xiaogpt.py 后，控制台能打印出问的问题，但没法继续就挂了

### ISSUE THREAD

**Issue by woiweb** [yihong0618/xiaogpt#279]
` python3 xiaogpt.py --hardware LX04  --mute_xiaoai --use_gpt3                

Running xiaogpt now, 用`帮我/请回答`开头来提问
或用`开始持续对话`开始持续对话
--------------------
问题：一加一等于几？
Traceback (most recent call last):
  File "/Users/xiaoqiang/Market/dev/gpt/xiaogpt/xiaogpt.py", line 5, in <module>
    main()
  File "/Users/xiaoqiang/Market/dev/gpt/xiaogpt/xiaogpt/cli.py", line 136, in main
    loop.run_until_complete(miboy.run_forever())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/xiaoqiang/Market/dev/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 466, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/Users/xiaoqiang/Market/dev/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 408, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xiaoqiang/Market/dev/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 399, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MiNAService' object has no attribute 'player_get_status'`

**Comment by yihong0618** [comment]
1. 最好不用  --use_gpt3 用 chatgpt
2. pip uninstall miservice 
3. pip install miservice_fork

**Comment by woiweb** [comment]
> 1. 最好不用  --use_gpt3 用 chatgpt
> 2. pip uninstall miservice
> 3. pip install miservice_fork

嗯，试过了，好像还是不行，

![image](https://github.com/yihong0618/xiaogpt/assets/715007/aa026d25-0b11-4042-9482-9cecb22aaa19)


python3 xiaogpt.py --hardware LX04  --mute_xiaoai --use_chatgpt_api

`Running xiaogpt now, 用`帮我/请回答`开头来提问
或用`开始持续对话`开始持续对话
--------------------
问题：请问明天的天气如何？
Traceback (most recent call last):
  File "/Users/xiaoqiang/Market/dev/gpt/xiaogpt/xiaogpt.py", line 5, in <module>
    main()
  File "/Users/xiaoqiang/Market/dev/gpt/xiaogpt/xiaogpt/cli.py", line 136, in main
    loop.run_until_complete(miboy.run_forever())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/xxt/dev/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 466, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/Users/xxt/dev/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 408, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xx/dev/gpt/xiaogpt/xiaogpt/xiaogpt.py", line 399, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MiNAService' object has no attribute 'player_get_status'`

**Comment by yihong0618** [comment]
我们是不是可以学一下举一反三。。。
python -m pip uninstall miservice
python -m pip install miservice_fork

**Comment by yihong0618** [comment]
![image](https://github.com/yihong0618/xiaogpt/assets/15976103/4be8f481-e9b4-40fb-a615-a55d8771ec27)
