### ISSUE TITLE
ROM端未响应

### ISSUE THREAD

**Issue by jiangyanfeng** [yihong0618/xiaogpt#309]
Running xiaogpt now, 用`请问`开头来提问
或用`开始持续对话`开始持续对话

--------------------
问题：明天星期几？
Traceback (most recent call last):
  File "/usr/local/bin/xiaogpt", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/xiaogpt/cli.py", line 153, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/xiaogpt/xiaogpt.py", line 470, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/usr/local/lib/python3.8/dist-packages/xiaogpt/xiaogpt.py", line 414, in stop_if_xiaoai_is_playing
    await self.mina_service.player_pause(self.device_id)
  File "/usr/local/lib/python3.8/dist-packages/miservice/minaservice.py", line 52, in player_pause
    return await self.ubus_request(
  File "/usr/local/lib/python3.8/dist-packages/miservice/minaservice.py", line 32, in ubus_request
    result = await self.mina_request(
  File "/usr/local/lib/python3.8/dist-packages/miservice/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
  File "/usr/local/lib/python3.8/dist-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 101, 'message': 'ubus server or device returned invalid result', 'data': {'device_data': '{"msg":"ROM端未响应","code":3012}', 'reqID': 'app_ios_****************************'}}
Task was destroyed but it is pending!
task: <Task pending name='Task-7' coro=<MiGPT.poll_latest_ask() running at /usr/local/lib/python3.8/dist-packages/xiaogpt/xiaogpt.py:102> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f4aac5ff520>()]>>
Exception ignored in: <coroutine object MiGPT.poll_latest_ask at 0x7f4aac46adc0>

**Comment by yihong0618** [comment]
@jiangyanfeng 用最新的再试试？

**Comment by yihong0618** [comment]
重启小爱
