### ISSUE TITLE
用EdgeGPT，使用代理会报错，新版EdgeGPT v0.13.2修复了这个问题。

### ISSUE THREAD

**Issue by shidesheng** [yihong0618/xiaogpt#341]
使用EdgeGPT旧版本，使用代理报错用不了，新版EdgeGPT v0.13.2修复了报错。建议大佬更新下EdgeGPT组件版本。

**Comment by yihong0618** [comment]
@shidesheng 好的 
来个 PR？

**Comment by shidesheng** [comment]
> @shidesheng 好的 来个 PR？

我也没调好，改用新版EdgeGPT：

```
import asyncio, json
from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle
```

报错了：
`Traceback (most recent call last):
  File "/root/app/xiaogpt/./xiaogpt.py", line 5, in <module>
    main()
  File "/root/app/xiaogpt/xiaogpt/cli.py", line 165, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/app/xiaogpt/xiaogpt/xiaogpt.py", line 481, in run_forever
    if not self.chatbot.history:
  File "/root/app/xiaogpt/xiaogpt/xiaogpt.py", line 187, in chatbot
    self._chatbot = get_bot(self.config)
  File "/root/app/xiaogpt/xiaogpt/bot/__init__.py", line 22, in get_bot
    return BOTS[config.bot].from_config(config)
  File "/root/app/xiaogpt/xiaogpt/bot/newbing_bot.py", line 30, in from_config
    return cls(
  File "/root/app/xiaogpt/xiaogpt/bot/newbing_bot.py", line 23, in __init__
    self._bot = Chatbot(
TypeError: __init__() got an unexpected keyword argument 'cookiePath'
`

**Comment by shidesheng** [comment]
大佬帮忙看下，咋更新模块。@yihong0618

**Comment by yihong0618** [comment]
edge 不支持了，下个版本我们去掉
