### ISSUE TITLE
播报报错argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by kk565** [yihong0618/xiaogpt#369]
之前用着一直挺好的。最近开始报错。已经更新到最新容器了，仍然报错。

日志如下：

Running xiaogpt now, 用`请问/帮我`开头来提问
或用`开始持续对话`开始持续对话
--------------------
问题：天空为什么是蓝色的？
以下是小爱的回答:
光是由七色光复合而成的：红橙黄绿蓝靛紫。简单的讲蓝色光易分散折射。所以天空呈现蓝
色。
以下是 CHATGPTAPI 的回答: argument of type 'NoneType' is not iterable
[11/08/23 14:16:11] ERROR    haha                                 xiaogpt.py:353
                             Traceback (most recent call last):
                               File "/app/xiaogpt/xiaogpt.py",
                             line 351, in run_tts
                                 url, duration = await
                             self.text2mp3(text, tts_lang)
                               File "/app/xiaogpt/xiaogpt.py",
                             line 343, in text2mp3
                                 raise RuntimeError(f"Failed to
                             get tts from edge with
                             voice={tts_lang}")
                             RuntimeError: Failed to get tts from
                             edge with voice=zh-CN-YunxiaNeural
回答完毕
^CTraceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 177, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)

**Comment by kk565** [comment]
重启不管用

**Comment by yihong0618** [comment]
chatgpt 挂了。。。

**Comment by white586** [comment]
谢谢哥们

**Comment by yihong0618** [comment]
不客气
