### ISSUE TITLE
Error https://api.io.mi.com/app/home/device_list: Login failed

### ISSUE THREAD

**Issue by erbanku** [yihong0618/xiaogpt#38]
你好，我用 [Yonsm/MiService](https://github.com/Yonsm/MiService/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) 获取设备ID时出现了以下错误，请问这该怎么解决呢？

先把账号密码导出了一下（用如下命令，保证账号密码正确）：
```
export MI_USER="A"
export MI_PASS="B"
```
然后运行获取账号信息的命令，就这样了（在不同Linux机器上都试了一下，还是一样的结果）：
```
[03/02/2023 18:33:47]root@azs-debian-jpeast:~/workspace/MiService$ ./micli.py list
Exception on login 2505813677: 'userId'
Traceback (most recent call last):
  File "/root/workspace/MiService/miservice/miaccount.py", line 71, in login
    self.token['userId'] = resp['userId']
KeyError: 'userId'
Error https://api.io.mi.com/app/home/device_list: Login failed
[03/02/2023 18:33:52]root@azs-debian-jpeast:~/workspace/MiService$
```

**Comment by yihong0618** [comment]
尝试

1. rm ~/.mi.token 再重复以上的步骤
2. 都不行的话换网试一试。

**Comment by erbanku** [comment]
> 尝试
> 
> 1. rm ~/.mi.token 再重复以上的步骤
> 2. 都不行的话换网试一试。

还是不行🤔

```
[03/02/2023 18:40:38]root@azs-debian-jpeast:~/workspace/MiService$ rm ~/.mi.token
rm: cannot remove '/root/.mi.token': No such file or directory
[03/02/2023 19:24:23]root@azs-debian-jpeast:~/workspace/MiService$ export MI_USER="A"
[03/02/2023 19:24:50]root@azs-debian-jpeast:~/workspace/MiService$ export MI_PASS="B"
[03/02/2023 19:25:05]root@azs-debian-jpeast:~/workspace/MiService$ ./micli.py list
Exception on login erbanku@gmail.com: 'userId'
Traceback (most recent call last):
  File "/root/workspace/MiService/miservice/miaccount.py", line 71, in login
    self.token['userId'] = resp['userId']
KeyError: 'userId'
Error https://api.io.mi.com/app/home/device_list: Login failed
[03/02/2023 19:25:09]root@azs-debian-jpeast:~/workspace/MiService$ 
```

**Comment by yihong0618** [comment]
直接使用步骤 10 如果还是不行确保下账号密码正确。

**Comment by joe12801** [comment]
测试过了，不能国外服务器，只能国内服务器才可以登录成功小米后台了

**Comment by erbanku** [comment]
> 测试过了，不能国外服务器，只能国内服务器才可以登录成功小米后台了

@joe12801 感谢！
@yihong0618 确实是这个问题，换一个国内服务器就好了。

**Comment by yihong0618** [comment]
我感觉是能的，得改下代码，把里面的 url 换成相应的国家，我有时间做下

**Comment by joe12801** [comment]
记得改下哈，目前，只有中国能用，其它国外的服务器都用不了

**Comment by yihong0618** [comment]
@joe12801 我看看。

**Comment by lingfengchencn** [comment]
这个功能好像依然没有可以？在国外的服务器就不能跑。
