### ISSUE TITLE
docker执行报错

### ISSUE THREAD

**Issue by lornice** [yihong0618/xiaogpt#392]
Traceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 171, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/xiaogpt/xiaogpt.py", line 344, in run_forever
    await self.init_all_data(session)
  File "/app/xiaogpt/xiaogpt.py", line 80, in init_all_data
    await self._init_data_hardware()
  File "/app/xiaogpt/xiaogpt.py", line 119, in _init_data_hardware
    raise Exception(
Exception: we have no hardware: lx01 please use `micli mina` to check

**Comment by lornice** [comment]
lx要改成大写LX

**Comment by yihong0618** [comment]
啊对！谢谢
