### ISSUE TITLE
小爱音响play docker部署的glm开始用的好好的，突然错误/app/xiaogpt/xiaogpt.py:55，请教大佬

### ISSUE THREAD

**Issue by lossor** [yihong0618/xiaogpt#409]
Traceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 171, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/xiaogpt/xiaogpt.py", line 388, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/app/xiaogpt/xiaogpt.py", line 332, in stop_if_xiaoai_is_playing
    await self.mina_service.player_pause(self.device_id)
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 52, in player_pause
    return await self.ubus_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 32, in ubus_request
    result = await self.mina_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 101, 'message': 'ubus server or device returned invalid result', 'data': {'device_data': '{"msg":"ROM端未响应","code":3012}', 'reqID': 'app_ios_zu------------'}}ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-7' coro=<MiGPT.poll_latest_ask() done, defined at /app/xiaogpt/xiaogpt.py:55> exception=Exception('Error https://api2.mina.mi.com/remote/ubus: {\'code\': 101, \'message\': \'ubus server or device returned invalid result\', \'data\': {\'device_data\': \'{"msg":"ROM端未响应","code":3012}\', \'reqID\': \'app_ios_coekl------2\'}}')>

**Comment by yihong0618** [comment]
重启小爱

**Comment by lossor** [comment]
激动!!!大佬现身!!重新pull了一遍，解决了.

**Comment by yihong0618** [comment]
关了哈
