### ISSUE TITLE
Ubuntu-desktop中部署文问题的时候，就报错退出了，什么原因啊，麻烦大佬给看下吧

### ISSUE THREAD

**Issue by tianxi2023** [yihong0618/xiaogpt#434]
xtx@xtx-ubuntu:~/my_code/xiaogpt$ python3 xiaogpt.py --hardware LX06 --use_chatgpt_api --mute_xiaoai
Running xiaogpt now, 用帮我/请开头来提问
或用开始持续对话开始持续对话
--------------------
问题：请问中国足球何时才能捧起大力神杯？
Traceback (most recent call last):
  File "/home/xtx/my_code/xiaogpt/xiaogpt.py", line 5, in <module>
    main()
  File "/home/xtx/my_code/xiaogpt/xiaogpt/cli.py", line 204, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/xtx/my_code/xiaogpt/xiaogpt/xiaogpt.py", line 388, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/home/xtx/my_code/xiaogpt/xiaogpt/xiaogpt.py", line 329, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "/home/xtx/my_code/xiaogpt/xiaogpt/xiaogpt.py", line 320, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
AttributeError: 'MiNAService' object has no attribute 'player_get_status'
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<MiGPT.poll_latest_ask() done, defined at /home/xtx/my_code/xiaogpt/xiaogpt/xiaogpt.py:55> exception=AttributeError("'MiNAService' object has no attribute 'player_get_status'")>
Traceback (most recent call last):
  File "/home/xtx/my_code/xiaogpt/xiaogpt/xiaogpt.py", line 71, in poll_latest_ask
    await self.stop_if_xiaoai_is_playing()
  File "/home/xtx/my_code/xiaogpt/xiaogpt/xiaogpt.py", line 329, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "/home/xtx/my_code/xiaogpt/xiaogpt/xiaogpt.py", line 320, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
AttributeError: 'MiNAService' object has no attribute 'player_get_status'

**Comment by yihong0618** [comment]
pip uninstall miservice
pip install miservice-fork

**Comment by tianxi2023** [comment]
好的，感谢大佬，这个问题解决了，现在又出现新问题，gpt回答提示connection error。这是因为网络连接的问题，还是因为墙的问题，我用openwrt订阅节点，ubuntu的网关用的openwrt的，应该不是墙的原因吧。还得麻烦您给看一下
以下是输出：
xtx@xtx-ubuntu:~/my_code/xiaogpt$ python3 xiaogpt.py --hardware LX06 --use_chatgpt_api --mute_xiaoai
Running xiaogpt now, 用帮我/请开头来提问
或用开始持续对话开始持续对话
--------------------
问题：请问中国足球何时才能捧起大力神杯？
以下是小爱的回答:  被你问住了，看来要更努力学习了
以下是 ChatGPT 的回答: Connection error.
回答完毕

**Comment by yihong0618** [comment]
你得放 openai key  啊

**Comment by tianxi2023** [comment]
openaikey我配置了，用export这个命令配置的
![image](https://github.com/yihong0618/xiaogpt/assets/122082064/bd677b47-400d-4234-b80e-14d4d374ce62)

**Comment by yihong0618** [comment]
你需要，你得确保本地能跑 ChatGPT terminal 能跑

**Comment by tianxi2023** [comment]
好的，我再研究下，谢谢了！
