### ISSUE TITLE
docker 报错

### ISSUE THREAD

**Issue by superwiboy** [yihong0618/xiaogpt#435]
调用千问

Traceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 200, in main
    config = Config.from_options(options)
  File "/app/xiaogpt/config.py", line 126, in from_options
    config = cls.read_from_file(options.config)
  File "/app/xiaogpt/config.py", line 136, in read_from_file
    config = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 3 (char 328)

**Comment by yihong0618** [comment]
得保证 config 是合法的 json 格式。

**Comment by superwiboy** [comment]
设置错了~~/(ㄒoㄒ)/~~
