### ISSUE TITLE
求助: windows11系统上, xiaogpt服务无法启动?

### ISSUE THREAD

**Issue by ccjeaty** [yihong0618/xiaogpt#447]
```shell

C:\Users>python --version
Python 3.8.1

C:\Users>set MI_USER=xxx

C:\Users>set MI_PASS=xxx

C:\Users>set MI_DID=15xxxx

C:\Users>pip install -U --force-reinstall xiaogpt
Collecting xiaogpt
  Downloading https://files.pythonhosted.org/packages/04/5f/23fbbc631025b1023093c9405f659fa3fcd86f19f012d7a2a18a9e5b3be1/xiaogpt-2.2-py3-none-any.whl
.....
  Running setup.py install for google-search-results ... done
Successfully installed BingImageCreator-0.5.0 EdgeGPT-0.1.26 PyYAML-6.0.1 SQLAlchemy-2.0.27 aiohttp-3.9.3 aiosignal-1.3.1 annotated-types-0.6.0 anyio-4.3.0 async-timeout-4.0.3 attrs-23.2.0 bardapi-0.1.39 beautifulsoup4-4.12.3 cachetools-5.3.2 certifi-2024.2.2 charset-normalizer-3.3.2 colorama-0.4.6 dataclasses-json-0.6.4 distro-1.9.0 edge-tts-6.1.10 exceptiongroup-1.2.0 frozenlist-1.4.1 google-search-results-2.4.2 greenlet-3.0.3 h11-0.14.0 httpcore-1.0.3 httpx-0.26.0 idna-3.6 jsonpatch-1.33 jsonpointer-2.4 langchain-0.1.8 langchain-community-0.0.21 langchain-core-0.1.24 langsmith-0.1.3 markdown-it-py-3.0.0 marshmallow-3.20.2 mdurl-0.1.2 miservice-fork-2.3.4 multidict-6.0.5 mutagen-1.47.0 mypy-extensions-1.0.0 numexpr-2.8.6 numpy-1.24.4 openai-1.12.0 packaging-23.2 prompt-toolkit-3.0.43 pydantic-2.6.1 pydantic-core-2.16.2 pygments-2.17.2 pyjwt-2.8.0 regex-2023.12.25 requests-2.31.0 rich-13.7.0 sniffio-1.3.0 soupsieve-2.5 tenacity-8.2.3 tqdm-4.66.2 typing-extensions-4.9.0 typing-inspect-0.9.0 urllib3-2.2.1 wcwidth-0.2.13 websockets-12.0 xiaogpt-2.2 yarl-1.9.4 zhipuai-2.0.1
WARNING: You are using pip version 19.2.3, however version 24.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


C:\Users>xiaogpt --hardware S12 --use_chatgpt_api
Traceback (most recent call last):
  File "d:\programs\_coding\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\programs\_coding\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Programs\_coding\Python38\Scripts\xiaogpt.exe\__main__.py", line 5, in <module>
    from xiaogpt.cli import main
  File "d:\programs\_coding\python38\lib\site-packages\xiaogpt\cli.py", line 5, in <module>
    from xiaogpt.xiaogpt import MiGPT
  File "d:\programs\_coding\python38\lib\site-packages\xiaogpt\xiaogpt.py", line 18, in <module>
    from xiaogpt.bot import get_bot
  File "d:\programs\_coding\python38\lib\site-packages\xiaogpt\bot\__init__.py", line 8, in <module>
    from xiaogpt.bot.bard_bot import BardBot
  File "d:\programs\_coding\python38\lib\site-packages\xiaogpt\bot\bard_bot.py", line 6, in <module>
    from bardapi import BardAsync
  File "d:\programs\_coding\python38\lib\site-packages\bardapi\__init__.py", line 4, in <module>
    from bardapi.core import Bard
  File "d:\programs\_coding\python38\lib\site-packages\bardapi\core.py", line 30, in <module>
    from bardapi.models.result import BardResult
  File "d:\programs\_coding\python38\lib\site-packages\bardapi\models\result.py", line 3, in <module>
    from bardapi.models.draft import BardDraft
  File "d:\programs\_coding\python38\lib\site-packages\bardapi\models\draft.py", line 14, in <module>
    from bardapi.models.tools.youtube import BardYoutubeContent
  File "d:\programs\_coding\python38\lib\site-packages\bardapi\models\tools\youtube.py", line 38, in <module>
    class BardYoutubeContent(UserContent):
  File "d:\programs\_coding\python38\lib\site-packages\bardapi\models\tools\youtube.py", line 63, in BardYoutubeContent
    def videos(self) -> list[BardYoutubeVideo]:
TypeError: 'type' object is not subscriptable
```

另外看了下issue里面其他S12的, 启动好像都不是我这样的, 是不是我哪里操作不正确

**Comment by yihong0618** [comment]
same as https://github.com/yihong0618/xiaogpt/issues/438

**Comment by ccjeaty** [comment]
> same as #438

好的. 我晚点试试升级python3.9
