### ISSUE TITLE
使用docker 部署，

### ISSUE THREAD

**Issue by ansonken** [yihong0618/xiaogpt#465]
igest: sha256:6b4dfa346b189ef0248b295083077b294310249fc9edb718b71754f47e88bfe3
Status: Downloaded newer image for yihong0618/xiaogpt:latest
Traceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 204, in main
    loop.run_until_complete(miboy.run_forever())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/xiaogpt/xiaogpt.py", line 346, in run_forever
    await self.init_all_data(self.mi_session)
  File "/app/xiaogpt/xiaogpt.py", line 81, in init_all_data
    await self._init_data_hardware()
  File "/app/xiaogpt/xiaogpt.py", line 120, in _init_data_hardware
    raise Exception(
Exception: we have no hardware: l09a please use `micli mina` to check

我的小爱音箱的型号是L09a

**Comment by ansonken** [comment]
"name": "小爱音箱Art",
    "model": "xiaomi.wifispeaker.l09a",

**Comment by yihong0618** [comment]
这个型号不支持
