### ISSUE TITLE
No module named 'aiohttp'

### ISSUE THREAD

**Issue by lingxide** [yihong0618/xiaogpt#47]
Hello,

In below evironment there is a chance that 'aiohttp' module is missing and requires to get installed in advance:

```
(py3) [root@Edge xiaogpt]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
(py3) [root@Edge xiaogpt]# python3 -V
Python 3.10.4
(py3) [root@Edge xiaogpt]#
```

Issues when 'aiohttp' is not installed:

```
(py3) [root@Edge xiaogpt]# pip3 install -r requirements.txt
Collecting git+https://github.com/yihong0618/MiService (from -r requirements.txt (line 2))
  Cloning https://github.com/yihong0618/MiService to /tmp/pip-req-build-0u7ehtjb
  Running command git clone --quiet https://github.com/yihong0618/MiService /tmp/pip-req-build-0u7ehtjb
  Resolved https://github.com/yihong0618/MiService to commit c8f245207c25817116086729b924e3c15fd4385c
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-0u7ehtjb/setup.py", line 15, in <module>
          from miservice import MISERVICE_VERSION
        File "/tmp/pip-req-build-0u7ehtjb/miservice/__init__.py", line 1, in <module>
          from .miaccount import MiAccount, MiTokenStore
        File "/tmp/pip-req-build-0u7ehtjb/miservice/miaccount.py", line 9, in <module>
          from aiohttp import ClientSession
      ModuleNotFoundError: No module named 'aiohttp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(py3) [root@Edge xiaogpt]# 
```
As a resolution I would suggest to add **aiohttp** in requirements.txt

**Comment by yihong0618** [comment]
@lingxide Fix thanks

**Comment by yihong0618** [comment]
@lingxide I think it's OK closing now
