### ISSUE TITLE
docker运行报错ubus server or device returned invalid result

### ISSUE THREAD

**Issue by white586** [yihong0618/xiaogpt#512]
yihong0618/xiaogpt                 latest    08dc5cf73a4b

最新docker，昨天晚上运行还好好的。

今天早上报错。见如下日志。是不是小米服务器挂了

```
Running xiaogpt now, 用请问/帮我开头来提问
或用开始持续对话开始持续对话
--------------------
问题：天空为什么是蓝色的？
Traceback (most recent call last):
  File "/app/xiaogpt.py", line 5, in <module>
    main()
  File "/app/xiaogpt/cli.py", line 233, in main
    loop.run_until_complete(main(config))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/xiaogpt/cli.py", line 228, in main
    await miboy.run_forever()
  File "/app/xiaogpt/xiaogpt.py", line 399, in run_forever
    await self.stop_if_xiaoai_is_playing()
  File "/app/xiaogpt/xiaogpt.py", line 333, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "/app/xiaogpt/xiaogpt.py", line 324, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 92, in player_get_status
    return await self.ubus_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 48, in ubus_request
    result = await self.mina_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 38, in mina_request
    return await self.account.mi_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 101, 'message': 'ubus server or device returned invalid result', 'data': {'device_data': '{"msg":"ROM端未响应","code":3012}', 'reqID': 'app_ios_FZKiCJnWdso4tA2maOvzSYRMrceTg7'}}
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<MiGPT.poll_latest_ask() done, defined at /app/xiaogpt/xiaogpt.py:58> exception=Exception('Error https://api2.mina.mi.com/remote/ubus: {\'code\': 101, \'message\': \'ubus server or device returned invalid result\', \'data\': {\'device_data\': \'{"msg":"ROM端未响应","code":3012}\', \'reqID\': \'app_ios_FNiqsVBSdEUpCXYnPfTy5ADj1o96bI\'}}')>
Traceback (most recent call last):
  File "/app/xiaogpt/xiaogpt.py", line 76, in poll_latest_ask
    await self.stop_if_xiaoai_is_playing()
  File "/app/xiaogpt/xiaogpt.py", line 333, in stop_if_xiaoai_is_playing
    is_playing = await self.get_if_xiaoai_is_playing()
  File "/app/xiaogpt/xiaogpt.py", line 324, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 92, in player_get_status
    return await self.ubus_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 48, in ubus_request
    result = await self.mina_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/minaservice.py", line 38, in mina_request
    return await self.account.mi_request(
  File "/app/.venv/lib/python3.10/site-packages/miservice/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 101, 'message': 'ubus server or device returned invalid result', 'data': {'device_data': '{"msg":"ROM端未响应","code":3012}', 'reqID': 'app_ios_FNiqsVBSdEUpCXYnPfTy5ADj1o96bI'}}
```

**Comment by yihong0618** [comment]
重启小爱再跑下

**Comment by white586** [comment]
谢谢，好像是服务器挂了，后来也没有重启，自己好了

**Comment by yihong0618** [comment]
好的
