### ISSUE TITLE
import error when running `xiaogpt.py`

### ISSUE THREAD

**Issue by xiyu23** [yihong0618/xiaogpt#522]
Environment: windows 10
shell: bash

```sh
$ py xiaogpt.py --hardware L06A --use_chatgpt_api
Traceback (most recent call last):
  File "D:\code\....\....\xiaogpt\xiaogpt.py", line 18, in <module>
    from xiaogpt.bot import get_bot
  File "D:\code\....\....\xiaogpt\xiaogpt.py", line 18, in <module>
    from xiaogpt.bot import get_bot
ModuleNotFoundError: No module named 'xiaogpt.bot'; 'xiaogpt' is not a package
```

**Comment by xiyu23** [comment]
Close
