### ISSUE TITLE
为什么pycharm不能直接运行xiaogpt.py，执行pip install -U后cmd下执行xiaogpt命令即可

### ISSUE THREAD

**Issue by weifeng2020** [yihong0618/xiaogpt#527]
D:\py_pro\XIAOMI\xiaogptv2\venv\Scripts\python.exe D:\py_pro\XIAOMI\xiaogptv2\xiaogpt\xiaogpt.py 
Traceback (most recent call last):
  File "D:\py_pro\XIAOMI\xiaogptv2\xiaogpt\xiaogpt.py", line 17, in <module>
    from xiaogpt.bot import get_bot
  File "D:\py_pro\XIAOMI\xiaogptv2\xiaogpt\xiaogpt.py", line 17, in <module>
    from xiaogpt.bot import get_bot
ModuleNotFoundError: No module named 'xiaogpt.bot'; 'xiaogpt' is not a package

**Comment by weifeng2020** [comment]
已解决
