### ISSUE TITLE
这是登录错误？

### ISSUE THREAD

**Issue by laihongzhu** [yihong0618/xiaogpt#62]
Running xiaogpt now, 用`帮我`开头来提问
2023-03-04 20:39:32,002 - miservice - ERROR - login - Exception on login : {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "C:\Users\86173\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\miservice\miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
2023-03-04 20:39:32,082 - miservice - ERROR - login - Exception on login : {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "C:\Users\86173\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\miservice\miaccount.py", line 69, in login
    raise Exception(resp)
Exception: {'qs': '%3Fsid%3Dmicoapi%26_json%3Dtrue', 'code': 70016, 'description': '登录验证失败', 'securityStatus': 0, '_sign': '58VY7HzpBxBcLsgTGFWDyJ7fEtw=', 'sid': 'micoapi', 'result': 'error', 'captchaUrl': None, 'callback': 'https://api2.mina.mi.com/sts', 'location': '', 'pwd': 0, 'child': 0, 'desc': '登录验证失败'}
Traceback (most recent call last):
  File "F:\xiaochat\xiaogpt\xiaogpt.py", line 457, in <module>
    asyncio.run(miboy.run_forever())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\xiaochat\xiaogpt\xiaogpt.py", line 288, in run_forever
    await self.init_all_data(session)
  File "F:\xiaochat\xiaogpt\xiaogpt.py", line 140, in init_all_data
    await self._init_data_hardware()
  File "F:\xiaochat\xiaogpt\xiaogpt.py", line 164, in _init_data_hardware
    hardware_data = await self.mina_service.device_list()
  File "C:\Users\86173\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\miservice\minaservice.py", line 27, in device_list
    result = await self.mina_request("/admin/v2/device_list?master=" + str(master))
  File "C:\Users\86173\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\miservice\minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
  File "C:\Users\86173\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\miservice\miaccount.py", line 149, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_B6DKLqt9uYivmyIWUhElXVMFgdGZAO: Login failed

**Comment by yihong0618** [comment]
是的
请先确保 micli list work

**Comment by sanzhier82** [comment]
我也是一样的问题，卡在这里，谁能帮解决下，有偿求助。

**Comment by roostinghawk** [comment]
> 我也是一样的问题，卡在这里，谁能帮解决下，有偿求助。
你的 MI_DID 都正常拿到了吗？

**Comment by laihongzhu** [comment]
> > 我也是一样的问题，卡在这里，谁能帮助解决下，有忌求助。
> > 你的MI_DID都正常拿来了吗？

能拿到

**Comment by yihong0618** [comment]
登陆验证失败，报错是，确保能跑 micli list 和 micli mina
